"use client";
import { useEffect, useRef, useState } from "react";
import { pairedPass, type Assessment } from "../examples/arena/assessments";
import { ARENA_SETUP_VERSION, MAX_RUNS, performanceSeries, runMetrics, type ArenaRun, type PerformanceMetric, type SavedFixture } from "../examples/arena/history";
const value = (n: number | null, metric: PerformanceMetric) => n === null ? "Unknown" : metric === "duration" ? `${(n / 1000).toFixed(1)} s` : n.toLocaleString();
export const runTime = (at: string) => new Date(at).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit" });
export function ArenaHistory({ runs, assessments, fixture, selectedId, pending, error, onOpen, onClear, onCompare }: {
  runs: ArenaRun[]; assessments: Assessment[]; fixture: SavedFixture; selectedId: string | null; pending: boolean; error: string | null;
  onOpen: (run: ArenaRun) => void; onClear: () => Promise<boolean>; onCompare: () => void;
}) {
  const [metric, setMetric] = useState<PerformanceMetric>("input"), [confirm, setConfirm] = useState(false);
  const [reviewedOnly, setReviewedOnly] = useState(false);
  const chart = useRef<HTMLElement>(null);
  const [chartWidth, setChartWidth] = useState(840);
  const related = runs.filter(run => run.fixture.id === fixture.id);
  const { points, excluded } = performanceSeries(reviewedOnly ? runs.filter(run => pairedPass(assessments.find(a => a.runId === run.id))) : runs, fixture, metric);
  const hasChart = points.length > 0;
  // Filtering can replace the figure without changing the runs or metric.
  useEffect(() => { const node = chart.current; if (!node) return; const observer = new ResizeObserver(entries => { const width = entries[0]?.contentRect.width; if (width) setChartWidth(Math.max(250, Math.min(1200, width))); }); observer.observe(node); return () => observer.disconnect(); }, [hasChart]);
  const reviewed = related.filter(run => { const a = assessments.find(a => a.runId === run.id); return a && a.baseline !== "unreviewed" && a.integrated !== "unreviewed"; });
  const passing = related.filter(run => pairedPass(assessments.find(a => a.runId === run.id))).length;
  const max = Math.max(1, ...points.flatMap(point => [point.baseline, point.integrated]));
  const x = (index: number) => points.length === 1 ? chartWidth / 2 : 50 + index / (points.length - 1) * (chartWidth - 70);
  const axisTime = (at: string) => chartWidth < 480 ? new Date(at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : runTime(at);
  const y = (n: number) => 180 - n / max * 135;
  const last = points.at(-1), first = points[0];
  const median = (values: number[]) => { const sorted = [...values].sort((a, b) => a - b), mid = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2; };
  return <section className="history-panel" aria-label="Local run history">
    <div className="history-heading"><div><p className="eyebrow">Saved in this browser</p><h2>Performance over time</h2><p className="hint">{fixture.title} · {related.length} saved {related.length === 1 ? "run" : "runs"}</p></div><div className="history-metric" role="group" aria-label="Performance metric">{([['input', 'Input tokens'], ['duration', 'Time']] as const).map(([id, label]) => <button key={id} aria-pressed={metric === id} onClick={() => setMetric(id)}>{label}</button>)}</div></div>
    <div className="history-review-filter"><div><strong>{reviewed.length} of {related.length} reviewed</strong><span>{passing} marked Meets task in both lanes · {reviewed.length - passing} reviewed {reviewed.length - passing === 1 ? "pair needs" : "pairs need"} work</span></div><label><input type="checkbox" checked={reviewedOnly} onChange={event => setReviewedOnly(event.target.checked)} />Chart only pairs marked Meets task</label></div>
    {error && <p className="cache-error" role="status">{error}</p>}
    {!related.length ? <div className="history-empty"><span aria-hidden="true">↗</span><h3>Your next run starts the timeline</h3><p>Run the same example again to compare both agents over time. Results stay here after refresh.</p><button className="quiet" onClick={onCompare}>Go to comparison</button></div> : <>
      <div className="history-stats"><div><span>Comparable runs</span><strong>{points.length}</strong></div><div><span>Median · without Jev</span><strong>{points.length ? value(median(points.map(p => p.baseline)), metric) : "Unknown"}</strong></div><div><span>Median · with Jev</span><strong>{points.length ? value(median(points.map(p => p.integrated)), metric) : "Unknown"}</strong></div></div>
      {points.length ? <figure className="history-chart" ref={chart}><div className="trend-key"><span>Without Jev</span><span>With Jev · includes routing</span></div><svg viewBox={`0 0 ${chartWidth} 225`} role="img" aria-labelledby="trend-title trend-description"><title id="trend-title">{metric === "input" ? "Reported input tokens" : "CLI plus routing duration"} across {points.length} completed {points.length === 1 ? "run" : "runs"}</title><desc id="trend-description">Oldest to newest. Exact paired values and dates are listed below. {excluded} runs excluded because results, measurements or matching setup are missing.</desc>
        {[0, .5, 1].map(fraction => <g key={fraction}><line x1="50" x2={chartWidth - 20} y1={y(max * fraction)} y2={y(max * fraction)} className="trend-grid" /><text x="40" y={y(max * fraction) + 4} textAnchor="end">{metric === "duration" ? `${(max * fraction / 1000).toFixed(1)}s` : new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 1 }).format(max * fraction)}</text></g>)}
        {(["baseline", "integrated"] as const).map(id => <g key={id} className={`trend-${id}`}><polyline points={points.map((point, index) => `${x(index)},${y(point[id])}`).join(" ")} fill="none" />{points.map((point, index) => <circle key={point.run.id} cx={x(index)} cy={y(point[id])} r={selectedId === point.run.id ? 5 : 3.5} />)}</g>)}
        <text x="50" y="211">{first ? axisTime(first.run.finishedAt) : ""}</text><text x={chartWidth - 20} y="211" textAnchor="end">{points.length > 1 && last ? axisTime(last.run.finishedAt) : ""}</text>
      </svg><figcaption>{points.length === 1 ? "One result is a starting point. Run this example again to see a trend." : "Each point is one saved comparison, ordered by completion time; horizontal spacing is by run, not elapsed time."} {reviewedOnly && "Chart filtered by your human assessments; all runs remain listed below."} {excluded > 0 && `${excluded} ${excluded === 1 ? "run is" : "runs are"} excluded from this chart and its medians.`}</figcaption></figure> : <p className="history-empty-note">No complete, comparable measurements yet. The saved results below still contain the evidence that was returned.</p>}
      <div className="history-run-list" aria-label="Saved comparisons"><div className="history-list-labels" aria-hidden="true"><span>Run</span><span>Without Jev</span><span>With Jev</span><span /></div>{related.map(run => { const values = runMetrics(run, metric); const comparable = points.some(point => point.run.id === run.id); const assessment = assessments.find(a => a.runId === run.id); const assessmentLabel = assessment ? pairedPass(assessment) ? "both meet task" : assessment.baseline === "fail" || assessment.integrated === "fail" ? "needs work" : "review incomplete" : "unreviewed"; return <button key={run.id} className={`history-run ${selectedId === run.id ? "selected" : ""}`} disabled={pending} onClick={() => onOpen(run)} aria-label={`Open ${runTime(run.finishedAt)}, ${run.status} comparison. Without Jev: ${value(values.baseline, metric)}${metric === "input" ? " input tokens" : ""}. With Jev including routing: ${value(values.integrated, metric)}${metric === "input" ? " input tokens" : ""}. ${comparable ? "Charted." : "Not charted."} Human assessment: ${assessmentLabel}.`}><span><time dateTime={run.finishedAt}>{runTime(run.finishedAt)}</time><small>{run.status === "complete" ? "Completed" : run.status === "cancelled" ? "Cancelled" : run.status === "partial" ? "Partial results" : "Failed"}{!comparable ? " · not charted" : ""}{run.setupVersion !== ARENA_SETUP_VERSION ? " · different setup" : ""}{` · ${assessmentLabel}`}</small></span><span><small className="mobile-metric-label">Without Jev</small>{value(values.baseline, metric)}</span><span><small className="mobile-metric-label">With Jev</small>{value(values.integrated, metric)}</span><span className="history-open" aria-hidden="true">Open ↗</span></button>; })}</div>
    </>}
    <div className="history-footer"><p>Up to {MAX_RUNS} runs within 2 MB, stored on this device and origin. Includes answers and receipts; no API keys. Same task and harness setup only in trends. CLI defaults and cache effects can change between runs; quality is not scored automatically. Human assessments remain separate annotations.</p>{confirm ? <div className="history-clear"><span>Clear all {runs.length} saved runs and their assessments?</span><button className="quiet" onClick={async () => { if (await onClear()) setConfirm(false); }}>Clear history</button><button className="quiet" onClick={() => setConfirm(false)}>Keep history</button></div> : <button className="quiet" disabled={pending || (!runs.length && !error)} onClick={() => setConfirm(true)}>Clear local history</button>}</div>
  </section>;
}
